import AppKit
import SwiftUI

/// Riwayat clipboard: teks, tautan, dan gambar yang terakhir di-copy. Teks & tautan disimpan di
/// UserDefaults Mac ini (maks. 40); gambar hanya di memori selama app berjalan (maks. 8).
/// Isi yang ditandai rahasia/sementara oleh pengelola kata sandi (konvensi nspasteboard.org)
/// tidak pernah dicatat.
@MainActor
final class ClipboardHistory: ObservableObject {
    enum Kind: String, Codable { case text, link, image }

    struct Item: Identifiable, Equatable {
        let id: UUID
        let kind: Kind
        let text: String?
        let image: NSImage?
        let imageData: Data?
        let app: String?
        let date: Date

        static func == (a: Item, b: Item) -> Bool { a.id == b.id }
    }

    private struct Stored: Codable {
        let id: UUID
        let kind: Kind
        let text: String
        let app: String?
        let date: Date
    }

    @Published private(set) var items: [Item] = []

    private let pasteboard = NSPasteboard.general
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?
    private let key = "clipboard.items"
    private static let skipped: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                                               "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    private static let maxText = 40, maxImages = 8, maxLength = 20_000

    init() {
        if let data = UserDefaults.standard.data(forKey: key), let saved = try? JSONDecoder().decode([Stored].self, from: data) {
            items = saved.map { Item(id: $0.id, kind: $0.kind, text: $0.text, image: nil, imageData: nil, app: $0.app, date: $0.date) }
        }
    }

    func setEnabled(_ enabled: Bool) {
        timer?.invalidate()
        timer = nil
        guard enabled else { return }
        lastChange = pasteboard.changeCount // yang di-copy sebelum fitur dinyalakan tidak dicatat
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    private func poll() {
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipped) else { return }
        let app = NSWorkspace.shared.frontmostApplication?.localizedName
        if let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty {
            let clipped = String(text.prefix(Self.maxLength))
            let isLink = URL(string: clipped).map { ["http", "https"].contains($0.scheme?.lowercased() ?? "") } == true && !clipped.contains(" ")
            add(Item(id: UUID(), kind: isLink ? .link : .text, text: clipped, image: nil, imageData: nil, app: app, date: Date()))
        } else if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), data.count < 20_000_000,
                  let image = NSImage(data: data) {
            add(Item(id: UUID(), kind: .image, text: nil, image: image, imageData: data, app: app, date: Date()))
        }
    }

    private func add(_ item: Item) {
        var next = items
        if let text = item.text { next.removeAll { $0.text == text } }
        next.insert(item, at: 0)
        let images = next.filter { $0.kind == .image }.dropFirst(Self.maxImages).map(\.id)
        next.removeAll { images.contains($0.id) }
        let texts = next.filter { $0.kind != .image }.dropFirst(Self.maxText).map(\.id)
        next.removeAll { texts.contains($0.id) }
        withAnimation(.notch) { items = next }
        save()
    }

    /// Salin lagi ke clipboard (dan naikkan ke paling atas).
    func copy(_ item: Item) {
        pasteboard.clearContents()
        if let text = item.text {
            pasteboard.setString(text, forType: .string)
        } else if let data = item.imageData {
            let png = data.starts(with: [0x89, 0x50, 0x4E, 0x47])
            pasteboard.setData(data, forType: png ? .png : .tiff)
        }
        lastChange = pasteboard.changeCount
        var next = items
        next.removeAll { $0.id == item.id }
        next.insert(item, at: 0)
        withAnimation(.notch) { items = next }
        save()
    }

    func remove(_ item: Item) {
        withAnimation(.notch) { items.removeAll { $0.id == item.id } }
        save()
    }

    func clear() {
        withAnimation(.notch) { items = [] }
        save()
    }

    private func save() {
        let stored = items.compactMap { item in item.text.map { Stored(id: item.id, kind: item.kind, text: $0, app: item.app, date: item.date) } }
        if let data = try? JSONEncoder().encode(stored) { UserDefaults.standard.set(data, forKey: key) }
    }

    // Untuk snapshot.
    func preview(_ texts: [String]) {
        items = texts.enumerated().map { i, text in
            Item(id: UUID(), kind: text.hasPrefix("http") ? .link : .text, text: text, image: nil, imageData: nil,
                 app: ["Safari", "Notes", "Pages"][i % 3], date: Date().addingTimeInterval(Double(-i) * 420))
        }
    }
}

struct ClipboardPanel: View {
    @ObservedObject var model: NotchModel
    @ObservedObject var history: ClipboardHistory
    @Environment(\.snapshot) private var snapshot

    private let columns = [GridItem(.flexible(), spacing: 8), GridItem(.flexible(), spacing: 8)]

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                SectionLabel(text: history.items.isEmpty ? L("Clipboard", "Clipboard") : "\(L("Clipboard", "Clipboard")) · \(history.items.count)")
                Spacer()
                if !history.items.isEmpty {
                    Button(L("Hapus semua", "Clear all")) { history.clear() }.buttonStyle(PillButtonStyle(prominent: false))
                }
            }
            if history.items.isEmpty {
                Placeholder(icon: "doc.on.clipboard", text: L("Yang kamu copy akan muncul di sini. Klik untuk copy lagi.",
                                                               "Things you copy show up here. Click to copy again."))
            } else if snapshot {
                grid
            } else {
                ScrollView(.vertical, showsIndicators: false) { grid }
            }
        }
    }

    private var grid: some View {
        LazyVGrid(columns: columns, alignment: .leading, spacing: 8) {
            ForEach(history.items) { item in
                ClipboardTile(item: item) {
                    history.copy(item)
                    model.show(.done(L("Disalin ke clipboard", "Copied to clipboard")))
                } remove: { history.remove(item) }
            }
        }
    }
}

private struct ClipboardTile: View {
    let item: ClipboardHistory.Item
    let copy: () -> Void
    let remove: () -> Void
    @State private var hover = false

    var body: some View {
        Button(action: copy) {
            HStack(alignment: .top, spacing: 8) {
                if let image = item.image {
                    Image(nsImage: image).resizable().aspectRatio(contentMode: .fill)
                        .frame(width: 34, height: 34).clipShape(RoundedRectangle(cornerRadius: 6))
                } else {
                    Image(systemName: item.kind == .link ? "link" : "text.alignleft")
                        .font(.system(size: 11, weight: .semibold)).foregroundStyle(Color.accent)
                        .frame(width: 22, height: 22)
                        .background(RoundedRectangle(cornerRadius: 6).fill(Color.accent.opacity(0.16)))
                }
                VStack(alignment: .leading, spacing: 2) {
                    Text(item.text ?? L("Gambar", "Image"))
                        .font(.system(size: 11.5, weight: .medium)).lineLimit(2).multilineTextAlignment(.leading)
                    Text([item.app, Relative.ago(item.date)].compactMap { $0 }.joined(separator: " · "))
                        .font(.system(size: 9.5)).foregroundStyle(.white.opacity(0.45)).lineLimit(1)
                }
                Spacer(minLength: 0)
            }
            .padding(8)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(RoundedRectangle(cornerRadius: 9).fill(Color.white.opacity(hover ? 0.12 : 0.07)))
            .overlay(alignment: .topTrailing) {
                if hover {
                    Button(action: remove) { Image(systemName: "xmark").font(.system(size: 8.5, weight: .bold)).padding(5) }
                        .buttonStyle(.plain).foregroundStyle(.white.opacity(0.6)).help(L("Hapus", "Remove"))
                }
            }
            .contentShape(Rectangle())
        }
        .buttonStyle(PressableStyle())
        .onHover { hover = $0 }
        .help(L("Klik untuk copy lagi", "Click to copy again"))
    }
}
